name: "dotnet-releaser action"
description: "Build, Test, Pack, Publish with dotnet-releaser"
inputs:
  dotnet-version:
    description: "The version of the .NET SDK to use"
    required: false
    default: |
      8.0.x
      9.0.x
  dotnet-releaser-path:
    description: "The path to the dotnet-releaser configuration file"
    required: false
    default: 'src/dotnet-releaser.toml'
  NUGET_TOKEN:
    description: "The NuGet API key"
    required: true
  PAT_GITHUB_TOKEN:
    description: "The GitHub Personal Access Token"
    required: false
  GIST_GITHUB_TOKEN:
    description: "The GitHub Personal Access Token for Gist"
    required: false

runs:
  using: 'composite'
  steps:
  - name: Checkout current repository
    uses: actions/checkout@v4
    with:
      submodules: true
      fetch-depth: 0

  - name: Checkout xoofx/.github
    uses: actions/checkout@v4
    with:
      repository: 'xoofx/.github'
      path: 'xoofx-github'
      ref: 'main'
      clean: false

  - name: Install .NET ${{ inputs.dotnet-version }}
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: ${{ inputs.dotnet-version }}

  - name: Build, Test, Pack, Publish
    shell: bash
    run: |
      dotnet tool install -g dotnet-releaser --configfile xoofx-github/.github/workflows/nuget_org_only.config
      dotnet-releaser run --nuget-token "${{inputs.NUGET_TOKEN}}" --github-token "${{inputs.PAT_GITHUB_TOKEN || github.token}}" --github-token-gist "${{inputs.GIST_GITHUB_TOKEN || inputs.PAT_GITHUB_TOKEN || github.token}}" ${{ inputs.dotnet-releaser-path }}
