on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: false
        default: 'ubuntu-latest'
      dotnet-version:
        type: string
        required: false
        default: |
          8.0.x
          9.0.x
          10.0.x
      dotnet-releaser-path:
        type: string
        required: false
        default: 'src/dotnet-releaser.toml'

    secrets:
      NUGET_TOKEN:
        required: false
      PAT_GITHUB_TOKEN:
        required: false
      GIST_GITHUB_TOKEN:
        required: false

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}

    permissions:
      id-token: write
      actions: write
      contents: write

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v5
      with:
        submodules: true
        fetch-depth: 0

    - name: Checkout xoofx/.github
      uses: actions/checkout@v5
      with:
        repository: 'xoofx/.github'
        path: 'xoofx-github'
        ref: 'main'
        clean: false

    - name: Install .NET ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Build, Test, Pack, Publish
      shell: bash
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        DOTNET_RELEASER_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN || github.token }}
        DOTNET_RELEASER_GIST_TOKEN: ${{ secrets.GIST_GITHUB_TOKEN || secrets.PAT_GITHUB_TOKEN || github.token }}
      run: |
        dotnet tool install -g dotnet-releaser --configfile xoofx-github/.github/workflows/nuget_org_only.config
        args=(run)
        if [ -n "${NUGET_TOKEN:-}" ]; then
          args+=(--nuget-token "$NUGET_TOKEN")
        fi
        args+=(--github-token "$DOTNET_RELEASER_GITHUB_TOKEN")
        args+=(--github-token-gist "$DOTNET_RELEASER_GIST_TOKEN")
        args+=("${{ inputs.dotnet-releaser-path }}")
        dotnet-releaser "${args[@]}"
